@host = http://localhost:3202

# "Marketing": "663693af02ea6db5c7908464",
# "Finanzas": "6636941102ea6db5c7908466",
# "Emprendimiento": "6636942602ea6db5c7908468",
# "Legal": "6636943a02ea6db5c790846a",
# "Programación": "6636945702ea6db5c790846c",
# "Diseño": "6636946d02ea6db5c790846e",

### Create category
POST {{host}}/category
Content-Type: application/json


{
  "title": "Diseño",
  "description": "Esta categoría incluye prompts relacionados con la creación de diseños visuales, experiencia de usuario, branding y diseño gráfico. Abarca temas como selección de paletas de color, composición de layouts, diseño de interfaces, creación de logotipos y desarrollo de identidad de marca. Estos prompts ayudarán a los usuarios a mejorar la apariencia y la usabilidad de sus productos y servicios."
}

### All categories
GET {{host}}/category
Content-Type: application/json

### Category by Id 
GET {{host}}/category/663693af02ea6db5c7908464
Content-Type: application/json

### Update category
PUT {{host}}/category/6636946d02ea6db5c790846e
Content-Type: application/json

{
  "title": "Diseño",
  "description": "Esta categoría incluye prompts relacionados con la creación de diseños visuales, experiencia de usuario, branding y diseño gráfico. Abarca temas como selección de paletas de color, composición de layouts, diseño de interfaces, creación de logotipos y desarrollo de identidad de marca. Estos prompts ayudarán a los usuarios a mejorar la apariencia y la usabilidad de sus productos y servicios."
}