@host = http://localhost:3202

### Create category
POST {{host}}/category
Content-Type: application/json

{
  "title": "Moda",
  "description": "Moda test"
}

### All categories
GET {{host}}/category
Content-Type: application/json

### Category by Id 
GET {{host}}/category/663693af02ea6db5c7908464
Content-Type: application/json

### Update category
PUT {{host}}/category/66369b8b08288bd5b656f505
Content-Type: application/json

{
  "descriptio": "Esta categoría incluye prompts relacionados con la gestión y el desarrollo de negocios, abarcando temas como planificación estratégica, marketing, finanzas, recursos humanos y emprendimiento. Estos prompts ayudarán a los usuarios a mejorar sus habilidades empresariales, a crear planes de negocio sólidos, a desarrollar estrategias de captación de clientes y a tomar decisiones financieras informadas. Los prompts en esta categoría están diseñados para impulsar el crecimiento y el éxito de las empresas, ya sean pequeñas, medianas o grandes.",
  "bgColor": "#edebfe",
  "textColor": "#6c2bd9"
}