@host = http://localhost:3202

### Create platform
POST {{host}}/platform
Content-Type: application/json


{
  "name": "Chat GPT",
  "url": "https://chatgpt.com/"
}

### All platform
GET {{host}}/platform
Content-Type: application/json

### platform by Id 
GET {{host}}/platform/663693af02ea6db5c7908464
Content-Type: application/json

### Update platform
PUT {{host}}/platform/6636946d02ea6db5c790846e
Content-Type: application/json

{
  "title": "Diseño",
  "description": "Esta categoría incluye prompts relacionados con la creación de diseños visuales, experiencia de usuario, branding y diseño gráfico. Abarca temas como selección de paletas de color, composición de layouts, diseño de interfaces, creación de logotipos y desarrollo de identidad de marca. Estos prompts ayudarán a los usuarios a mejorar la apariencia y la usabilidad de sus productos y servicios."
}