@host = http://localhost:3202

### Create platform
POST {{host}}/platform
Content-Type: application/json


{
  "code": "midjourney",
  "name": "Midjourney",
  "url": "https://www.midjourney.com/home",
  "logo": "https://en.wikipedia.org/wiki/File:Midjourney_Emblem.png#/media/File:Midjourney_Emblem.png"
}

### All platform
GET {{host}}/platform
Content-Type: application/json

### platform by Id 
GET {{host}}/platform/663693af02ea6db5c7908464
Content-Type: application/json

### Update platform
PUT {{host}}/platform/66369db9c8239b29feee4bf5
Content-Type: application/json

{
  "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/480px-ChatGPT_logo.svg.png"
}