@host = http://localhost:3202

### Create Prompt
POST {{host}}/prompt
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MzE0MjA4Zjg1YmVhN2M4NDNhYzhiZCIsInVzZXJuYW1lIjoiam9uIiwiZW1haWwiOiJqb25Aam9uLmNvbSIsImlhdCI6MTcxNDUwNTczN30.i50gvMkxgTY4tkYdf10m6NZUAQ4f-v9ETE7wz9MhlKo

{
  "title": "Para Marketing",
  "description": "Descripción detallada del uso del prompt.",
  "prompt": "Prompt de ejemplo",
  "createdBy": "62dafcb2f74d12d2f4d8c121", 
  "category": "6636945702ea6db5c790846c",
  "platforms": ["ChatGPT", "Leonardo"],
  "tags": ["ejemplo", "IA"]
}

### All prompts
GET {{host}}/prompt
Content-Type: application/json

### Prompt by Id 
GET {{host}}/prompt/663656f7ceee3bfadd4201be
Content-Type: application/json

### Upvote Prompt
POST {{host}}/prompt/663656f7ceee3bfadd4201be/upvote
Content-Type: application/json

### Update Prompt
PUT {{host}}/prompt/663656f7ceee3bfadd4201be
Content-Type: application/json

{
  "title": "Para Marketing Editado",
  "description": "Descripción detallada del uso del prompt editado.",
  "prompt": "Prompt de ejemplo PROMPET",
  "createdBy": "663698ab1e009d0176327186", 
  "category": "6636945702ea6db5c790846c",
  "platforms": ["ChatGPT", "Leonardo"],
  "tags": ["ejemplo", "IA"]
}