@host = http://localhost:3202

### Seed categories
GET {{host}}/seed/categories
Content-Type: application/json

### Seed users
GET {{host}}/seed/users
Content-Type: application/json
Authorization: Bearer {{process.env.HTTPYAC_ACCESS_TOKEN}}

### Seed prompts
GET {{host}}/seed/prompts
Content-Type: application/json


### Seed platforms
GET {{host}}/seed/platforms
Content-Type: application/json