"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var platform_controller_1 = require("./platform.controller");
var router = express_1.default.Router();
router.get("/", platform_controller_1.getAll);
router.get("/:id", platform_controller_1.getOneById);
router.post("/", platform_controller_1.create);
router.put("/:id", platform_controller_1.update);
exports.default = router;
